del *.ammdb /s /q
del *.bpm /s /q
del *.cdb /s /q
del *.dat /s /q
del *.db_info /s /q
del *.ddb /s /q
del *.hdb /s /q
del *.hier_info /s /q
del *.hif /s /q
del *.hsd /s /q
del *.idb /s /q
del *.ipinfo /s /q
del *.kpt /s /q
del *.logdb /s /q
del *.rdb /s /q
del *.sci /s /q
del *.tdb /s /q
del *.qmsg /s /q
del *.cbx.xml /s /q
del *.tmw_info /s /q
del *.dfp /s /q
del *.dpi /s /q
del *.hb_info /s /q
del *.rcfdb /s /q
del *.bak /s /q
del *.sdo /s /q
del *.vo /s /q
del *.vt /s /q
del *.wlf /s /q
del *.xrf /s /q
del *.sft /s /q
del *.do /s /q
del *.abo /s /q
del *.mif /s /q
del *.tdf /s /q
del *.rpt /s /q
del *.sof /s /q
del *.qdf /s /q
del *.summary /s /q
del *.done /s /q    
del *.smsg /s /q
del *.srf /s /q
del *.bak /s /q
